Release version 2.9.0
Signed-off-by: Rafael Julio <rafael.julio@mesalva.com>

diff --git a/keychain b/keychain
--- a/keychain
+++ b/keychain
@@ -13,7 +13,7 @@
 # Maintained July 2009 - Sept 2017 by Daniel Robbins <drobbins@funtoo.org>
 # Maintained September 2017 - present by Ryan Harris <x48rph@gmail.com>
 
-version=2.8.5
+version=2.9.0
 
 PATH="${PATH:-/usr/bin:/bin:/sbin:/usr/sbin:/usr/ucb}"
 
@@ -32,6 +32,7 @@ openssh=unknown
 sunssh=unknown
 confhost=unknown
 sshconfig=false
+confallhosts=false
 quickopt=false
 quietopt=false
 clearopt=false
@@ -39,6 +40,7 @@ color=true
 inheritwhich=local-once
 unset stopwhich
 unset timeout
+unset agent_socket
 unset ssh_timeout
 attempts=1
 unset sshavail
@@ -128,10 +130,11 @@ versinfo() {
 helpinfo() {
 	cat >&1 <<EOHELP
 SYNOPSIS
-    keychain [ ${GREEN}-hklQqV${OFF} ] [ ${GREEN}--clear${OFF} ${GREEN}--confhost${OFF} ${GREEN}--gpg2${OFF} ${GREEN}--help${OFF} ${GREEN}--ignore-missing${OFF}
-     ${GREEN}--list${OFF} ${GREEN}--noask${OFF} ${GREEN}--nocolor${OFF} ${GREEN}--nogui${OFF} ${GREEN}--nolock${OFF} ${GREEN}--quick${OFF} ${GREEN}--quiet${OFF} ${GREEN}--version${OFF} ]
-    [ ${GREEN}--agents${OFF} ${CYAN}list${OFF} ] [ ${GREEN}--attempts${OFF} ${CYAN}num${OFF} ] [ ${GREEN}--dir${OFF} ${CYAN}dirname${OFF} ]
-    [ ${GREEN}--host${OFF} ${CYAN}name${OFF} ] [ ${GREEN}--lockwait${OFF} ${CYAN}seconds${OFF} ]
+    keychain [ ${GREEN}-hklQqV${OFF} ] [ ${GREEN}--clear${OFF} ${GREEN}--confhost${OFF} ${GREEN}--confallhosts${OFF} ${GREEN}--gpg2${OFF} ${GREEN}--help${OFF} -
+    ${GREEN}-ignore-missing${OFF} ${GREEN}--list${OFF}
+    ${GREEN}--noask${OFF} ${GREEN}--nocolor${OFF} ${GREEN}--nogui${OFF} ${GREEN}--nolock${OFF} ${GREEN}--quick${OFF} ${GREEN}--quiet${OFF} ${GREEN}--version${OFF} ]
+    [ ${GREEN}--agents${OFF} ${CYAN}list${OFF} ] [ ${GREEN}--agent-socket${OFF} ${CYAN}list${OFF} ] [ ${GREEN}--attempts${OFF} ${CYAN}num${OFF} ]
+    [ ${GREEN}--dir${OFF} ${CYAN}dirname${OFF} ] [ ${GREEN}--host${OFF} ${CYAN}name${OFF} ] [ ${GREEN}--lockwait${OFF} ${CYAN}seconds${OFF} ]
     [ ${GREEN}--stop${OFF} ${CYAN}which${OFF} ] [ ${GREEN}--timeout${OFF} ${CYAN}minutes${OFF} ] [ keys... ]
 
 OPTIONS
@@ -139,6 +142,10 @@ OPTIONS
         Start the agents listed. By default keychain will start ssh-agent if
         it is found in your path. The list should be comma-separated, for
         example "gpg,ssh"
+
+    ${GREEN}--agent-socket${OFF} ${CYAN}path${OFF}
+        Path for SSH_AUTH_SOCK. If set, ssh-agent will try to bind the
+        socket to the given path.
 
     ${GREEN}--attempts${OFF} ${CYAN}num${OFF}
         Try num times to add keys before giving up. The default is 1.
@@ -153,8 +160,14 @@ OPTIONS
     ${GREEN}--confhost${OFF}
         By default, keychain will look for key pairs in the ~/.ssh/
         directory. The ${GREEN}--confhost${OFF} option will inform keychain to look in
-        ~/.ssh/config for IdentityFile settings defined for particular
-        hosts, and use these paths to locate keys.
+        ~/.ssh/config for IdentityFile settings defined for the mentioned
+        host (in ${CYAN}keys${OFF}), and use these paths to locate keys.
+
+    ${GREEN}--confallhosts${OFF}
+        By default, keychain will look for key pairs in the ~/.ssh/
+        directory. The ${GREEN}--confallhosts${OFF} option will inform keychain to look in
+        ~/.ssh/config for IdentityFile settings defined for all hosts, and
+        use these paths to locate keys to load.
 
     ${GREEN}--confirm${OFF}
         Keys are subject to interactive confirmation by the SSH_ASKPASS
@@ -268,7 +281,7 @@ OPTIONS
                  Prior to keychain-2.5.0, this was the behavior of the bare
                  "--stop" option.
 
-        others   Kill agent processes other than the one keychain is
+        others   Kill agent processes other than the ones keychain is
                  providing. Prior to keychain-2.5.0, keychain would do this
                  automatically. The new behavior requires that you specify
                  it explicitly if you want it.
@@ -789,7 +802,7 @@ startagent() {
 		# Branch again since the agents start differently
 		mesg "Starting ${start_prog}-agent..."
 		if [ "$start_prog" = ssh ]; then
-			start_out=$(ssh-agent ${ssh_timeout})
+			start_out=$(ssh-agent ${ssh_timeout} ${ssh_agent_socket})
 		elif [ "$start_prog" = gpg ]; then
 			if [ -n "${timeout}" ]; then
 				gpg_cache_ttl="$(expr $timeout \* 60)"
@@ -1034,7 +1047,15 @@ ssh_listmissing() {
 
 	for slm_k in "$@"; do
 		# Fingerprint current user-specified key
-		slm_finger=$(ssh_f "$slm_k") || continue
+		if ! slm_finger=$(ssh_f "$slm_k"); then
+			warn "Unable to extract fingerprint from keyfile ${slm_k}.pub, skipping"
+			continue
+		fi
+		slm_wordcount="$(printf -- '%s\n' "$slm_finger" | wc -w)"
+		if [ "$slm_wordcount" -ne 1 ]; then
+			warn "Unable to extract exactly one key fingerprint from keyfile ${slm_k}.pub, got $slm_wordcount instead, skipping"
+			continue
+		fi
 
 		# Check if it needs to be added
 		case " $sshavail " in
@@ -1074,8 +1095,10 @@ add_sshkey() {
 # synopsis: parse_mykeys
 # Sets $sshkeys and $gpgkeys based on $mykeys
 parse_mykeys() {
-	# Possible path to the private key: if --confhost variable used.
-	pkeypath="$1"
+  for pkeypath in "$@"; do
+    mykeys=${mykeys+"$mykeys
+"}"$pkeypath"
+  done
 
 	# Parse $mykeys into positional params to preserve spaces in filenames
 	set -f		   # disable globbing
@@ -1095,8 +1118,6 @@ parse_mykeys() {
 				add_sshkey "$HOME/.ssh/$pm_k" ; continue
 			elif [ -f "$HOME/.ssh2/$pm_k" ]; then
 				add_sshkey "$HOME/.ssh2/$pm_k" ; continue
-			elif [ -f "$pkeypath" ]; then
-				add_sshkey "$pkeypath"; continue
 			fi
 		fi
 
@@ -1140,7 +1161,7 @@ setagents() {
 		done
 		agentsopt="${new_agentsopt}"
 	else
-		for a in ssh; do
+		for a in ssh gpg; do
 			command -v ${a}-agent >/dev/null || continue
 			agentsopt="${agentsopt+$agentsopt }${a}"
 		done
@@ -1321,8 +1342,20 @@ while [ -n "$1" ]; do
 				warn "~/.ssh/config not found; --confhost/-c option ignored."
 			fi
 			;;
+    --confallhosts|-C)
+			if [ -e ~/.ssh/config ]; then
+				sshconfig=true
+        confallhosts=true
+			else
+				warn "~/.ssh/config not found; --confallhosts/-C option ignored."
+			fi
+			;;
 		--nocolor)
 			color=false
+			;;
+		--agent-socket)
+			shift
+			agent_socket=$1
 			;;
 		--timeout)
 			shift
@@ -1484,6 +1517,11 @@ fi
 # If there are no agents remaining, then bow out now...
 [ -n "$agentsopt" ] || { qprint; exit 0; }
 
+# --agent-socket translates argument into `-a` argument to set static SSH_AUTH_SOCKET
+if [ -n "$timeout" ] && wantagent ssh; then
+	ssh_agent_socket="-a $agent_socket"
+fi
+
 # --timeout translates almost directly to ssh-add/ssh-agent -t, but ssh.com uses
 # minutes and OpenSSH uses seconds
 if [ -n "$timeout" ] && wantagent ssh; then
@@ -1553,16 +1591,32 @@ fi
 # --noask: "don't ask for keys", so we're all done
 $noaskopt && { qprint; exit 0; }
 
-# If the --confhost option used, determine the path to the private key as
-# written in the ~/.ssh/config and add it to ssh-add.
+# If the --confhost or the --confallhosts option used, and the .ssh/config
+# file exists, either load host key or all keys defined
 if $sshconfig; then
-	pkeypath=$(confpath "$confhost")
-	eval pkeypath=$pkeypath
+  if $confallhosts; then
+    # If the --confallhosts option used, load all the private keys defined in
+    # the .ssh/config file and add them to ssh-add
+    while IFS= read -r line; do
+      case $line in
+        *IdentityFile*)
+        currentpath="$(echo $line | awk '{print $2}')"
+        eval currentpath=$currentpath
+        pkeypaths=${pkeypaths+"$pkeypaths
+"}"$currentpath"   
+      esac
+    done < ~/.ssh/config
+  else
+    # If the --confhost option is used, find the private key through 
+    # .ssh/config file and load it with ssh-add
+    pkeypaths=$(confpath "$confhost")
+	  eval pkeypaths=$pkeypaths
+  fi
 fi
 
 # Parse $mykeys into ssh vs. gpg keys; it may be necessary in the future to
 # differentiate on the cmdline
-parse_mykeys "$pkeypath" || die
+parse_mykeys "$pkeypaths" || die
 
 # Load ssh keys
 if wantagent ssh; then
